footprint: [[-0.1313, -0.21], [-0.1313, 0.21],[0.2887, 0.21], [0.2887, -0.21]]
#footprint: [[-0.283, -0.283], [-0.283, 0.283],[0.283, 0.283], [0.283, -0.283]]
#robot_radius: 0.314


obstacle_layer:
  enabled: true
  max_obstacle_height: 1.2
  min_obstacle_height: 0.0
  obstacle_range: 2.0
  raytrace_range: 5.0
  inflation_radius: 0.30
  combination_method: 1
  observation_sources: laser_scan_sensor # laser_scan_sensor_2 laser_scan_sensor_3 sonar_scan_sensor camera_depth
  track_unknown_space: true
 
  origin_z: 0.0
  z_resolution: 0.1
  z_voxels: 10
  unknown_threshold: 15
  mark_threshold: 0
  publish_voxel_map: true
  footprint_clearing_enabled: true
  observation_persistence: 0.0
#expected_update_rate: 0.2

  # laser_scan_sensor_2:
  #   data_type: LaserScan
  #   topic: /scan_2
  #   marking: true
  #   clearing: true
  #   expected_update_rate: 0
  #   min_obstacle_height: 0.01
  #   max_obstacle_height: 0.1

  # sonar_scan_sensor:
  #   data_type: PointCloud2
  #   topic: /sonar_cloudpoint
  #   marking: true
  #   clearing: true
  #   min_obstacle_height: 0.11
  #   max_obstacle_height: 0.2


  laser_scan_sensor:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    expected_update_rate: 0
    min_obstacle_height: 0.21
    max_obstacle_height: 0.30

  # laser_scan_sensor_3:
  #   data_type: LaserScan
  #   topic: /scan_3
  #   marking: true
  #   clearing: true
  #   expected_update_rate: 0
  #   min_obstacle_height: 0.31
  #   max_obstacle_height: 0.40

  # camera_depth:
  #   data_type: PointCloud2
  #   topic:  /camera/depth_registered/points   #/camera/depth/points #_filtered
  #   marking: ture
  #   clearing: true
  #   min_obstacle_height: 0.51
  #   max_obstacle_height: 1.4
    
inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.50 # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"

#virtualWall_layer:
#  enabled:              true
#  topic:  "/virtualWall_cloudPoint"
#  map_topic:            "/map"

# sonar_layer:
#   enabled:            true
#   clear_threshold:    0.2
#   mark_threshold:     0.8
#   topics: ["/sonar0", "/sonar1", "/sonar2", "/sonar3", "/sonar4"]
#   clear_on_max_reading: true
